# Archivo controllers que venia en el campero
# Es igual que el archivo ur10_controllers.yaml oficial que venia en el driver antiguo

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - campero_ur10_shoulder_pan_joint
     - campero_ur10_shoulder_lift_joint
     - campero_ur10_elbow_joint
     - campero_ur10_wrist_1_joint
     - campero_ur10_wrist_2_joint
     - campero_ur10_wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
pos_based_pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - campero_ur10_shoulder_pan_joint
     - campero_ur10_shoulder_lift_joint
     - campero_ur10_elbow_joint
     - campero_ur10_wrist_1_joint
     - campero_ur10_wrist_2_joint
     - campero_ur10_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      campero_ur10_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_elbow_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5
   
# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
vel_based_pos_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints:
     - campero_ur10_shoulder_pan_joint
     - campero_ur10_shoulder_lift_joint
     - campero_ur10_elbow_joint
     - campero_ur10_wrist_1_joint
     - campero_ur10_wrist_2_joint
     - campero_ur10_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      campero_ur10_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_elbow_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      campero_ur10_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   gains:
       #!!These values are useable, but maybe not optimal
      campero_ur10_shoulder_pan_joint: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
      campero_ur10_shoulder_lift_joint: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
      campero_ur10_elbow_joint: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
      campero_ur10_wrist_1_joint: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
      campero_ur10_wrist_2_joint: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
      campero_ur10_wrist_3_joint: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}


   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5
